In [2]:
from pathlib import Path
import zipfile
import numpy as np
import pandas as pd

In [3]:
PROJECT_PATH = Path.cwd().parent
print("Project Path", PROJECT_PATH.resolve())

Project Path D:\arc\Python\Python Projects\airline_operations_analytics

In [4]:
RAW_PATH = PROJECT_PATH / "01_Raw_Data"
RAW_PATH.mkdir(parents=True, exist_ok=True)
print("Raw_Path", RAW_PATH.resolve())
DOCUMENTATION_PATH = PROJECT_PATH / "02_Documentation"
DOCUMENTATION_PATH.mkdir(parents=True, exist_ok=True)
print("Documentation_Path", DOCUMENTATION_PATH.resolve())

Raw_Path D:\arc\Python\Python Projects\airline_operations_analytics\01_Raw_Data
Documentation_Path D:\arc\Python\Python Projects\airline_operations_analytics\02_Documentation

In [5]:
RAW_2024_PATH = RAW_PATH / "2024"
RAW_2024_PATH.mkdir(parents=True, exist_ok=True)
print("Raw_2024_Path", RAW_2024_PATH.resolve())
RAW_2025_PATH = RAW_PATH / "2025"
RAW_2025_PATH.mkdir(parents=True, exist_ok=True)
print("Raw_2025_Path", RAW_2025_PATH.resolve())

Raw_2024_Path D:\arc\Python\Python Projects\airline_operations_analytics\01_Raw_Data\2024
Raw_2025_Path D:\arc\Python\Python Projects\airline_operations_analytics\01_Raw_Data\2025

In [6]:
zip_files = list(RAW_2024_PATH.glob("*.zip"))
total_zip_file = len(zip_files)

print(f"Total Zip File: {total_zip_file}")

for file in zip_files:
    print("File Name:", file.name)
    print("File Size: ", round(file.stat().st_size/(1024 *1024),2), "MB")
    print("File Location", file.resolve())

Total Zip File: 12
File Name: On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_1.zip
File Size:  26.3 MB
File Location D:\arc\Python\Python Projects\airline_operations_analytics\01_Raw_Data\2024\On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_1.zip
File Name: On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_10.zip
File Size:  28.06 MB
File Location D:\arc\Python\Python Projects\airline_operations_analytics\01_Raw_Data\2024\On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_10.zip
File Name: On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_11.zip
File Size:  26.85 MB
File Location D:\arc\Python\Python Projects\airline_operations_analytics\01_Raw_Data\2024\On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_11.zip
File Name: On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_12.zip
File Size:  28.75 MB
File Location D:\arc\Python\Python Projects\airline_operations_analytics\01_Raw_Data\2024\On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_12.zip
File Name: On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_2.zip
File Size:  23.92 MB
File Location D:\arc\Python\Python Projects\airline_operations_analytics\01_Raw_Data\2024\On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_2.zip
File Name: On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_3.zip
File Size:  27.96 MB
File Location D:\arc\Python\Python Projects\airline_operations_analytics\01_Raw_Data\2024\On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_3.zip
File Name: On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_4.zip
File Size:  27.22 MB
File Location D:\arc\Python\Python Projects\airline_operations_analytics\01_Raw_Data\2024\On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_4.zip
File Name: On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_5.zip
File Size:  29.7 MB
File Location D:\arc\Python\Python Projects\airline_operations_analytics\01_Raw_Data\2024\On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_5.zip
File Name: On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_6.zip
File Size:  29.78 MB
File Location D:\arc\Python\Python Projects\airline_operations_analytics\01_Raw_Data\2024\On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_6.zip
File Name: On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_7.zip
File Size:  32.83 MB
File Location D:\arc\Python\Python Projects\airline_operations_analytics\01_Raw_Data\2024\On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_7.zip
File Name: On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_8.zip
File Size:  29.43 MB
File Location D:\arc\Python\Python Projects\airline_operations_analytics\01_Raw_Data\2024\On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_8.zip
File Name: On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_9.zip
File Size:  27.12 MB
File Location D:\arc\Python\Python Projects\airline_operations_analytics\01_Raw_Data\2024\On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_9.zip

In [7]:
zip_file = zip_files[0]

with zipfile.ZipFile(zip_file, "r") as z:
    files_inside_zip = z.namelist()

    for file in files_inside_zip:
        print(file)

On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_1.csv
readme.html

In [8]:
EXTRACT_PATH = RAW_2024_PATH / "January"

EXTRACT_PATH.mkdir(parents=True, exist_ok=True)

print("Extract_Path", EXTRACT_PATH.resolve())

Extract_Path D:\arc\Python\Python Projects\airline_operations_analytics\01_Raw_Data\2024\January

In [9]:
with zipfile.ZipFile(zip_file, "r") as z:
    z.extractall(EXTRACT_PATH)

In [10]:
csv_files = list(EXTRACT_PATH.rglob("*.csv"))

for files in csv_files:
    print(files)

d:\arc\Python\Python Projects\airline_operations_analytics\01_Raw_Data\2024\January\On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_1.csv

In [11]:
csv_file = csv_files[0]

df = pd.read_csv(
    csv_file,
    low_memory=False
)

In [12]:
df

,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,DOT_ID_Reporting_Airline,IATA_CODE_Reporting_Airline,Tail_Number,...,Div4TailNum,Div5Airport,Div5AirportID,Div5AirportSeqID,Div5WheelsOn,Div5TotalGTime,Div5LongestGTime,Div5WheelsOff,Div5TailNum,Unnamed: 109
0,2024,1,1,8,1,2024-01-08,9E,20363,9E,N485PX,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024,1,1,9,2,2024-01-09,9E,20363,9E,N912XJ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024,1,1,10,3,2024-01-10,9E,20363,9E,N918XJ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024,1,1,11,4,2024-01-11,9E,20363,9E,N490PX,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024,1,1,12,5,2024-01-12,9E,20363,9E,N915XJ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547266,2024,1,1,2,2,2024-01-02,UA,19977,UA,N411UA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
547267,2024,1,1,2,2,2024-01-02,UA,19977,UA,N426UA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
547268,2024,1,1,2,2,2024-01-02,UA,19977,UA,N77520,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
547269,2024,1,1,2,2,2024-01-02,UA,19977,UA,N446UA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
547270,2024,1,1,2,2,2024-01-02,UA,19977,UA,N849UA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df.head(10)

,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,DOT_ID_Reporting_Airline,IATA_CODE_Reporting_Airline,Tail_Number,...,Div4TailNum,Div5Airport,Div5AirportID,Div5AirportSeqID,Div5WheelsOn,Div5TotalGTime,Div5LongestGTime,Div5WheelsOff,Div5TailNum,Unnamed: 109
0,2024,1,1,8,1,2024-01-08,9E,20363,9E,N485PX,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024,1,1,9,2,2024-01-09,9E,20363,9E,N912XJ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024,1,1,10,3,2024-01-10,9E,20363,9E,N918XJ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024,1,1,11,4,2024-01-11,9E,20363,9E,N490PX,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024,1,1,12,5,2024-01-12,9E,20363,9E,N915XJ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2024,1,1,15,1,2024-01-15,9E,20363,9E,N485PX,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2024,1,1,16,2,2024-01-16,9E,20363,9E,N485PX,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2024,1,1,17,3,2024-01-17,9E,20363,9E,N482PX,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2024,1,1,18,4,2024-01-18,9E,20363,9E,N133EV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2024,1,1,19,5,2024-01-19,9E,20363,9E,N182GJ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
Total_Rows = df.shape[0]
print(Total_Rows)
Total_Columns = df.shape[1]
print(Total_Columns)

547271
110

In [19]:
df.columns

Index(['Year', 'Quarter', 'Month', 'DayofMonth', 'DayOfWeek', 'FlightDate',
       'Reporting_Airline', 'DOT_ID_Reporting_Airline',
       'IATA_CODE_Reporting_Airline', 'Tail_Number',
       ...
       'Div4TailNum', 'Div5Airport', 'Div5AirportID', 'Div5AirportSeqID',
       'Div5WheelsOn', 'Div5TotalGTime', 'Div5LongestGTime', 'Div5WheelsOff',
       'Div5TailNum', 'Unnamed: 109'],
      dtype='str', length=110)

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 547271 entries, 0 to 547270
Columns: 110 entries, Year to Unnamed: 109
dtypes: float64(68), int64(21), str(21)
memory usage: 459.3 MB

In [35]:
(df.isna().sum()/Total_Rows) * 100

Year                  0.0
Quarter               0.0
Month                 0.0
DayofMonth            0.0
DayOfWeek             0.0
                    ...
Div5TotalGTime      100.0
Div5LongestGTime    100.0
Div5WheelsOff       100.0
Div5TailNum         100.0
Unnamed: 109        100.0
Length: 110, dtype: float64